# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389829c6434f3ad50302327ae3384e0fd61526316bca779c09d88a93e8f60385a40adc13a03b888835d0cd2c10f56ecd4fa174ecf751bc5bc751d5f7d5a89036

test:
  secret_key_base: 183788d6eef1b8528bc17506912a94304ea750d471ab6fb8fbbcd94e085a16156adeecc086968507752f9ac85f1810f079772ed15ac250d1f3c6877d3a40046f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
